USER_POOL_ID = "us-east-1_IpvVz2oi0"
CLIENT_ID = "62ll0lotj3mb691ti15v5ak0mi"
REGION = "us-east-1"
ACCOUNT_ID = "245353047635"
IDENTITY_POOL_ID = "us-east-1:17318b0f-6555-4a66-b580-b1bf22277f33"
APPLICATION_ID = "9d6f7e5e-a491-4dd9-a1da-c6514cc83b7a"
USER_GROUP = "qbussinessgroup"